include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "lib/generated/**"
    - "build/**"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    # Disable rules that conflict with common patterns
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    flutter_style_todos: false
    
    # Enable useful rules
    prefer_single_quotes: true
    sort_constructors_first: true
    always_declare_return_types: true
    avoid_empty_else: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
